#pragma once

const uint8_t level1[MAP_FULL_SIZE] = {
  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
  EMPTY, EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, EMPTY,
  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, BABA,  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY,
  EMPTY, EMPTY, EMPTY, WALL,  W_WALL,W_IS,  W_STOP,EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY,
  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  FLAG,  EMPTY, EMPTY,
  EMPTY, EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, WALL,  EMPTY, EMPTY, EMPTY,
  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  WALL,  WALL,  EMPTY, EMPTY, EMPTY,
  W_FLAG,EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_BABA,
  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_IS,
  W_WIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_YOU,
};

const uint8_t level2[MAP_FULL_SIZE] = {
  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_ROCK,
  EMPTY, EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, EMPTY, EMPTY, W_IS,
  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, BABA,  WALL,  EMPTY, EMPTY, EMPTY, EMPTY, W_WIN,
  EMPTY, EMPTY, EMPTY, WALL,  W_WALL,W_IS,  W_STOP,WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
  EMPTY, EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_BABA,
  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_IS,
  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_YOU,
};

const uint8_t * levels[] = {
  level1, level2,
};

const uint8_t level_count = 2;
