#pragma once

const uint8_t level1[MAP_FULL_SIZE] = {
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, W_FLAG,W_IS,  W_WIN, EMPTY, EMPTY, EMPTY, W_WALL,W_IS,  W_STOP,EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, BABA,  EMPTY, EMPTY, EMPTY, ROCK,  EMPTY, EMPTY, EMPTY, FLAG,  EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, W_BABA,W_IS,  W_YOU, EMPTY, EMPTY, EMPTY, W_ROCK,W_IS,  W_PUSH,EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
};

const uint8_t level2[MAP_FULL_SIZE] = {
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, W_IS,  EMPTY, EMPTY, EMPTY, EMPTY, WALL,  
WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, EMPTY, EMPTY, W_WIN, EMPTY, WALL,  
WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  
WALL,  EMPTY, W_FLAG,EMPTY, EMPTY, EMPTY, FLAG,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  
WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, BABA,  EMPTY, EMPTY, WALL,  
WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, W_BABA,W_IS,  W_YOU, EMPTY, EMPTY, EMPTY, W_WALL,W_IS,  W_STOP,EMPTY, EMPTY, 
};

const uint8_t level3[MAP_FULL_SIZE] = {
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, W_BABA,EMPTY, EMPTY, EMPTY, EMPTY, W_FLAG,WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, 
EMPTY, W_IS,  EMPTY, EMPTY, EMPTY, EMPTY, W_IS,  WALL,  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
EMPTY, W_YOU, EMPTY, EMPTY, EMPTY, EMPTY, W_WIN, WALL,  EMPTY, FLAG,  EMPTY, WALL,  EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, 
EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
EMPTY, WALL,  EMPTY, W_WALL,W_IS,  W_STOP,EMPTY, EMPTY, BABA,  EMPTY, EMPTY, WALL,  EMPTY, 
EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, 
};

const uint8_t level4[MAP_FULL_SIZE] = {
W_BABA,WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  W_GOOP,
W_IS,  WALL,  EMPTY, EMPTY, EMPTY, W_ROCK,W_IS,  W_PUSH,EMPTY, EMPTY, EMPTY, WALL,  W_IS,  
W_YOU, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  W_SINK,
EMPTY, WALL,  EMPTY, BABA,  EMPTY, EMPTY, EMPTY, EMPTY, ROCK,  ROCK,  EMPTY, WALL,  EMPTY, 
EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
EMPTY, WALL,  WALL,  WALL,  WALL,  GOOP,  GOOP,  GOOP,  WALL,  WALL,  WALL,  WALL,  EMPTY, 
EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
W_WALL,WALL,  GOOP,  GOOP,  GOOP,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
W_IS,  WALL,  GOOP,  GOOP,  GOOP,  EMPTY, EMPTY, W_FLAG,W_IS,  W_WIN, EMPTY, WALL,  EMPTY, 
W_STOP,WALL,  FLAG,  GOOP,  GOOP,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
};

const uint8_t level5[MAP_FULL_SIZE] = {EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
W_BABA,EMPTY, EMPTY, ROCK,  EMPTY, EMPTY, EMPTY, ROCK,  EMPTY, EMPTY, EMPTY, EMPTY, W_WALL,
W_IS,  EMPTY, W_ROCK,W_IS,  W_PUSH,EMPTY, EMPTY, EMPTY, LAVA,  LAVA,  LAVA,  EMPTY, W_IS,  
W_YOU, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, LAVA,  FLAG,  LAVA,  EMPTY, W_STOP,
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, LAVA,  LAVA,  LAVA,  EMPTY, EMPTY, 
EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, EMPTY, ROCK,  EMPTY, EMPTY, EMPTY, 
EMPTY, WALL,  EMPTY, BABA,  EMPTY, ROCK,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_FLAG,
EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_IS,  
EMPTY, EMPTY, EMPTY, EMPTY, ROCK,  EMPTY, EMPTY, EMPTY, EMPTY, ROCK,  EMPTY, EMPTY, W_WIN, 
EMPTY, W_LAVA,W_IS,  W_KILL,EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
};

const uint8_t level6[MAP_FULL_SIZE] = {
W_LAVA,W_IS,  W_KILL,ROCK,  EMPTY, WALL,  LAVA,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, 
W_ROCK,W_IS,  W_STOP,ROCK,  EMPTY, WALL,  LAVA,  EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
W_FLAG,W_IS,  W_WIN, ROCK,  EMPTY, WALL,  LAVA,  EMPTY, EMPTY, FLAG,  EMPTY, WALL,  EMPTY, 
ROCK,  ROCK,  ROCK,  ROCK,  EMPTY, WALL,  LAVA,  EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  LAVA,  EMPTY, WALL,  WALL,  WALL,  WALL,  EMPTY, 
EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  LAVA,  
EMPTY, WALL,  BABA,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, WALL,  WALL,  WALL,  WALL,  W_WALL,W_IS,  W_STOP,WALL,  EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, W_BABA,W_IS,  W_YOU, WALL,  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, EMPTY, EMPTY, 
};

const uint8_t level7[MAP_FULL_SIZE] = {
EMPTY, EMPTY, EMPTY, EMPTY, W_WALL,W_IS,  W_STOP,EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  W_BABA,W_IS,  W_YOU, EMPTY, EMPTY, W_WIN, EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, W_FLAG,EMPTY, EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  BABA,  EMPTY, EMPTY, FLAG,  EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
};

const uint8_t level8[MAP_FULL_SIZE] = {
EMPTY, EMPTY, WALL,  BABA,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  LAVA,  LAVA,  LAVA,  EMPTY, EMPTY, W_WALL,EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, W_IS,  EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  EMPTY, W_LAVA,W_IS,  W_STOP,EMPTY, W_KILL,EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  WALL,  EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, W_FLAG,W_IS,  W_WIN, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 
EMPTY, EMPTY, W_WALL,W_IS,  W_STOP,EMPTY, EMPTY, EMPTY, W_BABA,W_IS,  W_YOU, EMPTY, EMPTY, 
};

const uint8_t * levels[] = {
  level1, level2, level3, level4, level5, level6, level7, level8
};

const uint8_t level_count = 8;
